[project]
name = "rankoder"
revision = "1.0"

[profiles.default]
RADARR_API_KEY = { description = "RADARR_API_KEY secret", required = true }
JELLYFIN_API_KEY = { description = "JELLYFIN_API_KEY secret", required = true }
